import { buildExpectedCheckpoints } from "../adapters/tracktozeroCalcAdapter";
import { createStartingDebtSnapshotItem } from "../../domain/tracktozero/models";

export const V2_TEST_ACTOR_ID = "seed-owner";
export const V2_TEST_NOW = "2026-08-13T12:00:00.000Z";

const planVersion = ({ id, planId, workspaceId, strategy, debts, extraMonthlyPayment, createdBy = V2_TEST_ACTOR_ID }) => ({
  id,
  planId,
  workspaceId,
  versionNumber: 1,
  strategy,
  asOf: V2_TEST_NOW,
  startingDebtSnapshot: debts.map(createStartingDebtSnapshotItem),
  extraMonthlyPayment,
  projectedZeroDate: "",
  createdAt: V2_TEST_NOW,
  createdBy,
  createdBecause: "activation",
});

export const createTrackToZeroV2Seed = () => {
  const personalDebts = [
    {
      id: "personal-capital-one",
      workspaceId: "personal-seed",
      name: "Capital One Card",
      debtType: "credit_card",
      status: "active",
      currentBalance: 2400,
      startingBalance: 2600,
      aprStatus: "known",
      apr: 0.2499,
      minimumRequiredPayment: 85,
      dueDay: 18,
      ownerId: V2_TEST_ACTOR_ID,
      ownerLabel: "You",
      includedInCorePayoffPlan: true,
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "personal-sofi",
      workspaceId: "personal-seed",
      name: "SoFi Personal Loan",
      debtType: "personal_loan",
      status: "active",
      currentBalance: 7800,
      startingBalance: 8100,
      aprStatus: "known",
      apr: 0.119,
      minimumRequiredPayment: 255,
      dueDay: 7,
      ownerId: V2_TEST_ACTOR_ID,
      ownerLabel: "You",
      includedInCorePayoffPlan: true,
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "personal-mortgage",
      workspaceId: "personal-seed",
      name: "Primary Mortgage",
      debtType: "mortgage",
      status: "active",
      currentBalance: 286000,
      startingBalance: 286000,
      aprStatus: "known",
      apr: 0.061,
      minimumRequiredPayment: 1840,
      dueDay: 1,
      ownerId: V2_TEST_ACTOR_ID,
      ownerLabel: "You",
      includedInCorePayoffPlan: false,
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
  ];

  const householdDebts = [
    {
      id: "household-priceline",
      workspaceId: "household-seed",
      name: "Priceline Card",
      debtType: "credit_card",
      status: "active",
      currentBalance: 4100,
      startingBalance: 4500,
      aprStatus: "known",
      apr: 0.2799,
      minimumRequiredPayment: 130,
      dueDay: 22,
      ownerId: "seed-admin",
      ownerLabel: "Baba",
      includedInCorePayoffPlan: true,
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "household-samsung",
      workspaceId: "household-seed",
      name: "Samsung Financing",
      debtType: "no_interest_plan",
      status: "active",
      currentBalance: 517,
      startingBalance: 620,
      aprStatus: "no_interest",
      apr: 0,
      minimumRequiredPayment: 45,
      dueDay: 12,
      ownerId: V2_TEST_ACTOR_ID,
      ownerLabel: "Jidye",
      includedInCorePayoffPlan: true,
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "household-mystery",
      workspaceId: "household-seed",
      name: "Old Store Card",
      debtType: "credit_card",
      status: "active",
      currentBalance: 930,
      startingBalance: 930,
      aprStatus: "unknown",
      apr: null,
      minimumRequiredPayment: 40,
      dueDay: 28,
      ownerId: "seed-admin",
      ownerLabel: "Baba",
      includedInCorePayoffPlan: true,
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
  ];

  const personalVersion = planVersion({
    id: "personal-version-1",
    planId: "personal-plan",
    workspaceId: "personal-seed",
    strategy: "avalanche",
    debts: personalDebts,
    extraMonthlyPayment: 150,
  });
  const householdVersion = planVersion({
    id: "household-version-1",
    planId: "household-plan",
    workspaceId: "household-seed",
    strategy: "snowball",
    debts: householdDebts,
    extraMonthlyPayment: 200,
  });

  const expectedCheckpoints = [
    ...buildExpectedCheckpoints({ debts: personalDebts, planVersion: personalVersion, startMonth: 8, startYear: 2026 }).slice(0, 24),
    ...buildExpectedCheckpoints({ debts: householdDebts, planVersion: householdVersion, startMonth: 8, startYear: 2026 }).slice(0, 24),
  ];

  return {
    workspaces: {
      "personal-seed": {
        id: "personal-seed",
        type: "personal",
        status: "active",
        activePlanId: "personal-plan",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
      },
      "household-seed": {
        id: "household-seed",
        type: "household",
        status: "active",
        activePlanId: "household-plan",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
      },
    },
    members: Object.fromEntries([
      ["personal-seed/seed-owner", { workspaceId: "personal-seed", uid: "seed-owner", role: "owner", displayName: "You", createdAt: V2_TEST_NOW }],
      ["household-seed/seed-owner", { workspaceId: "household-seed", uid: "seed-owner", role: "owner", displayName: "Jidye", createdAt: V2_TEST_NOW }],
      ["household-seed/seed-admin", { workspaceId: "household-seed", uid: "seed-admin", role: "admin", displayName: "Baba", createdAt: V2_TEST_NOW }],
      ["household-seed/seed-contributor", { workspaceId: "household-seed", uid: "seed-contributor", role: "contributor", displayName: "Contributor", createdAt: V2_TEST_NOW }],
      ["household-seed/seed-viewer", { workspaceId: "household-seed", uid: "seed-viewer", role: "viewer", displayName: "Viewer", createdAt: V2_TEST_NOW }],
    ]),
    debts: Object.fromEntries([...personalDebts, ...householdDebts].map((debt) => [`${debt.workspaceId}/${debt.id}`, debt])),
    plans: {
      "personal-seed/personal-plan": {
        id: "personal-plan",
        workspaceId: "personal-seed",
        status: "active",
        activeVersionId: "personal-version-1",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
        activatedAt: V2_TEST_NOW,
      },
      "household-seed/household-plan": {
        id: "household-plan",
        workspaceId: "household-seed",
        status: "active",
        activeVersionId: "household-version-1",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
        activatedAt: V2_TEST_NOW,
      },
    },
    versions: {
      "personal-seed/personal-plan/personal-version-1": personalVersion,
      "household-seed/household-plan/household-version-1": householdVersion,
    },
    balanceSnapshots: Object.fromEntries([
      ...personalDebts.filter((d) => d.includedInCorePayoffPlan !== false).map((debt) => [`${debt.workspaceId}/${debt.id}/snap-${debt.id}`, {
        id: `snap-${debt.id}`,
        workspaceId: debt.workspaceId,
        debtId: debt.id,
        balance: debt.currentBalance,
        observedAt: V2_TEST_NOW,
        source: "manual",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
      }]),
      ...householdDebts.map((debt) => [`${debt.workspaceId}/${debt.id}/snap-${debt.id}`, {
        id: `snap-${debt.id}`,
        workspaceId: debt.workspaceId,
        debtId: debt.id,
        balance: debt.currentBalance,
        observedAt: V2_TEST_NOW,
        source: "manual",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
      }]),
    ]),
    paymentEvents: {},
    expectedCheckpoints: Object.fromEntries(expectedCheckpoints.map((checkpoint) => [
      `${checkpoint.workspaceId}/${checkpoint.planId}/${checkpoint.planVersionId}/${checkpoint.id}`,
      checkpoint,
    ])),
  };
};
