import { buildExpectedCheckpoints } from "../adapters/tracktozeroCalcAdapter.js";
import { createStartingDebtSnapshotItem } from "../../domain/tracktozero/models.js";

export const V2_TEST_ACTOR_ID = "seed-owner";
export const V2_TEST_NOW = "2026-08-13T12:00:00.000Z";

const snapshotSeries = (workspaceId, debtId, entries = []) =>
  Object.fromEntries(
    entries.map((entry, index) => [
      `${workspaceId}/${debtId}/snap-${debtId}-${String(index + 1).padStart(2, "0")}`,
      {
        id: `snap-${debtId}-${String(index + 1).padStart(2, "0")}`,
        workspaceId,
        debtId,
        balance: entry.balance,
        observedAt: entry.observedAt,
        source: "manual",
        createdAt: entry.observedAt,
        createdBy: V2_TEST_ACTOR_ID,
      },
    ])
  );

const planVersion = ({ id, planId, workspaceId, strategy, debts, extraMonthlyPayment, createdBy = V2_TEST_ACTOR_ID }) => ({
  id,
  planId,
  workspaceId,
  versionNumber: 1,
  strategy,
  asOf: V2_TEST_NOW,
  startingDebtSnapshot: debts.map(createStartingDebtSnapshotItem),
  extraMonthlyPayment,
  projectedZeroDate: "",
  createdAt: V2_TEST_NOW,
  createdBy,
  createdBecause: "activation",
});

export const createTrackToZeroV2Seed = () => {
  const personalDebts = [
    {
      id: "personal-capital-one",
      workspaceId: "personal-seed",
      name: "Capital One Card",
      debtType: "credit_card",
      status: "active",
      currentBalance: 2400,
      startingBalance: 2600,
      aprStatus: "known",
      apr: 0.2499,
      minimumRequiredPayment: 85,
      dueDay: 18,
      ownerType: "member",
      ownerId: V2_TEST_ACTOR_ID,
      ownerLabel: "You",
      includedInCorePayoffPlan: true,
      openingBalanceSnapshotId: "snap-personal-capital-one",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "personal-sofi",
      workspaceId: "personal-seed",
      name: "SoFi Personal Loan",
      debtType: "personal_loan",
      status: "active",
      currentBalance: 7800,
      startingBalance: 8100,
      aprStatus: "known",
      apr: 0.119,
      minimumRequiredPayment: 255,
      dueDay: 7,
      ownerType: "member",
      ownerId: V2_TEST_ACTOR_ID,
      ownerLabel: "You",
      includedInCorePayoffPlan: true,
      openingBalanceSnapshotId: "snap-personal-sofi",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "personal-mortgage",
      workspaceId: "personal-seed",
      name: "Primary Mortgage",
      debtType: "mortgage",
      status: "active",
      currentBalance: 286000,
      startingBalance: 286000,
      aprStatus: "known",
      apr: 0.061,
      minimumRequiredPayment: 1840,
      dueDay: 1,
      ownerType: "member",
      ownerId: V2_TEST_ACTOR_ID,
      ownerLabel: "You",
      includedInCorePayoffPlan: false,
      openingBalanceSnapshotId: "snap-personal-mortgage",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
  ];

  const householdDebts = [
    {
      id: "household-priceline",
      workspaceId: "household-seed",
      name: "Priceline Card",
      debtType: "credit_card",
      status: "active",
      currentBalance: 4100,
      startingBalance: 4500,
      aprStatus: "known",
      apr: 0.2799,
      minimumRequiredPayment: 130,
      dueDay: 22,
      ownerType: "member",
      ownerId: "seed-admin",
      ownerLabel: "Baba",
      includedInCorePayoffPlan: true,
      openingBalanceSnapshotId: "snap-household-priceline",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "household-samsung",
      workspaceId: "household-seed",
      name: "Samsung Financing",
      debtType: "no_interest_plan",
      status: "active",
      currentBalance: 517,
      startingBalance: 620,
      aprStatus: "no_interest",
      apr: 0,
      minimumRequiredPayment: 45,
      dueDay: 12,
      ownerType: "member",
      ownerId: V2_TEST_ACTOR_ID,
      ownerLabel: "Jidye",
      includedInCorePayoffPlan: true,
      openingBalanceSnapshotId: "snap-household-samsung",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "household-mystery",
      workspaceId: "household-seed",
      name: "Old Store Card",
      debtType: "credit_card",
      status: "active",
      currentBalance: 930,
      startingBalance: 930,
      aprStatus: "unknown",
      apr: null,
      minimumRequiredPayment: 40,
      dueDay: 28,
      ownerType: "member",
      ownerId: "seed-admin",
      ownerLabel: "Baba",
      includedInCorePayoffPlan: true,
      openingBalanceSnapshotId: "snap-household-mystery",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "household-joint-loan",
      workspaceId: "household-seed",
      name: "Family Credit Union Loan",
      debtType: "personal_loan",
      status: "active",
      currentBalance: 6200,
      startingBalance: 6800,
      aprStatus: "known",
      apr: 0.0875,
      minimumRequiredPayment: 190,
      dueDay: 16,
      ownerType: "joint",
      ownerId: "",
      ownerLabel: "Joint / Household",
      includedInCorePayoffPlan: true,
      openingBalanceSnapshotId: "snap-household-joint-loan",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "household-jordan-card",
      workspaceId: "household-seed",
      name: "Jordan Travel Card",
      debtType: "credit_card",
      status: "active",
      currentBalance: 2400,
      startingBalance: 2700,
      aprStatus: "known",
      apr: 0.1899,
      minimumRequiredPayment: 88,
      dueDay: 9,
      ownerType: "person",
      ownerId: "person-jordan",
      ownerLabel: "Jordan Taylor",
      includedInCorePayoffPlan: true,
      openingBalanceSnapshotId: "snap-household-jordan-card",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "household-medical",
      workspaceId: "household-seed",
      name: "Clinic Payment Plan",
      debtType: "medical",
      status: "active",
      currentBalance: 1500,
      startingBalance: 1500,
      aprStatus: "no_interest",
      apr: 0,
      minimumRequiredPayment: 70,
      dueDay: 25,
      ownerType: "unassigned",
      ownerId: "",
      ownerLabel: "Unassigned",
      includedInCorePayoffPlan: true,
      openingBalanceSnapshotId: "snap-household-medical",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
    {
      id: "household-mortgage",
      workspaceId: "household-seed",
      name: "House Mortgage",
      debtType: "mortgage",
      status: "active",
      currentBalance: 120700,
      startingBalance: 121000,
      aprStatus: "known",
      apr: 0.059,
      minimumRequiredPayment: 1785,
      dueDay: 1,
      ownerType: "joint",
      ownerId: "",
      ownerLabel: "Joint / Household",
      includedInCorePayoffPlan: false,
      openingBalanceSnapshotId: "snap-household-mortgage",
      createdAt: V2_TEST_NOW,
      createdBy: V2_TEST_ACTOR_ID,
    },
  ];

  const personalVersion = planVersion({
    id: "personal-version-1",
    planId: "personal-plan",
    workspaceId: "personal-seed",
    strategy: "avalanche",
    debts: personalDebts,
    extraMonthlyPayment: 150,
  });
  const householdVersion = planVersion({
    id: "household-version-1",
    planId: "household-plan",
    workspaceId: "household-seed",
    strategy: "snowball",
    debts: householdDebts,
    extraMonthlyPayment: 200,
  });

  const expectedCheckpoints = [
    ...buildExpectedCheckpoints({ debts: personalDebts, planVersion: personalVersion, startMonth: 8, startYear: 2026 }).slice(0, 24),
    ...buildExpectedCheckpoints({ debts: householdDebts, planVersion: householdVersion, startMonth: 8, startYear: 2026 }).slice(0, 24),
  ];

  return {
    workspaces: {
      "personal-seed": {
        id: "personal-seed",
        type: "personal",
        status: "active",
        activePlanId: "personal-plan",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
      },
      "household-seed": {
        id: "household-seed",
        type: "household",
        status: "active",
        activePlanId: "household-plan",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
      },
    },
    members: Object.fromEntries([
      ["personal-seed/seed-owner", { workspaceId: "personal-seed", uid: "seed-owner", role: "owner", status: "active", displayName: "You", createdAt: V2_TEST_NOW }],
      ["household-seed/seed-owner", { workspaceId: "household-seed", uid: "seed-owner", role: "owner", status: "active", displayName: "Jidye", createdAt: V2_TEST_NOW }],
      ["household-seed/seed-admin", { workspaceId: "household-seed", uid: "seed-admin", role: "admin", status: "active", displayName: "Baba", createdAt: V2_TEST_NOW }],
      ["household-seed/seed-contributor", { workspaceId: "household-seed", uid: "seed-contributor", role: "contributor", status: "active", displayName: "Contributor", createdAt: V2_TEST_NOW }],
      ["household-seed/seed-viewer", { workspaceId: "household-seed", uid: "seed-viewer", role: "viewer", status: "active", displayName: "Viewer", createdAt: V2_TEST_NOW }],
    ]),
    people: {
      "household-seed/person-jordan": {
        id: "person-jordan",
        workspaceId: "household-seed",
        displayName: "Jordan Taylor",
        normalizedName: "jordan taylor",
        aliases: ["Jordan T"],
        kind: "imported_person",
        status: "active",
        source: "import_confirmed",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
      },
    },
    debts: Object.fromEntries([...personalDebts, ...householdDebts].map((debt) => [`${debt.workspaceId}/${debt.id}`, debt])),
    plans: {
      "personal-seed/personal-plan": {
        id: "personal-plan",
        workspaceId: "personal-seed",
        status: "active",
        activeVersionId: "personal-version-1",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
        activatedAt: V2_TEST_NOW,
      },
      "household-seed/household-plan": {
        id: "household-plan",
        workspaceId: "household-seed",
        status: "active",
        activeVersionId: "household-version-1",
        createdAt: V2_TEST_NOW,
        createdBy: V2_TEST_ACTOR_ID,
        activatedAt: V2_TEST_NOW,
      },
    },
    versions: {
      "personal-seed/personal-plan/personal-version-1": personalVersion,
      "household-seed/household-plan/household-version-1": householdVersion,
    },
    balanceSnapshots: {
      ...snapshotSeries("personal-seed", "personal-capital-one", [
        { balance: 2600, observedAt: "2026-06-15T12:00:00.000Z" },
        { balance: 2490, observedAt: "2026-07-15T12:00:00.000Z" },
        { balance: 2400, observedAt: V2_TEST_NOW },
      ]),
      ...snapshotSeries("personal-seed", "personal-sofi", [
        { balance: 8100, observedAt: "2026-06-15T12:00:00.000Z" },
        { balance: 7955, observedAt: "2026-07-15T12:00:00.000Z" },
        { balance: 7800, observedAt: V2_TEST_NOW },
      ]),
      ...snapshotSeries("personal-seed", "personal-mortgage", [
        { balance: 286000, observedAt: "2026-06-15T12:00:00.000Z" },
        { balance: 285400, observedAt: V2_TEST_NOW },
      ]),
      ...snapshotSeries("household-seed", "household-priceline", [
        { balance: 4500, observedAt: "2026-06-20T12:00:00.000Z" },
        { balance: 4325, observedAt: "2026-07-20T12:00:00.000Z" },
        { balance: 4100, observedAt: V2_TEST_NOW },
      ]),
      ...snapshotSeries("household-seed", "household-samsung", [
        { balance: 620, observedAt: "2026-06-20T12:00:00.000Z" },
        { balance: 565, observedAt: "2026-07-20T12:00:00.000Z" },
        { balance: 517, observedAt: V2_TEST_NOW },
      ]),
      ...snapshotSeries("household-seed", "household-mystery", [
        { balance: 930, observedAt: "2026-06-20T12:00:00.000Z" },
        { balance: 930, observedAt: V2_TEST_NOW },
      ]),
      ...snapshotSeries("household-seed", "household-joint-loan", [
        { balance: 6800, observedAt: "2026-06-20T12:00:00.000Z" },
        { balance: 6510, observedAt: "2026-07-20T12:00:00.000Z" },
        { balance: 6200, observedAt: V2_TEST_NOW },
      ]),
      ...snapshotSeries("household-seed", "household-jordan-card", [
        { balance: 2700, observedAt: "2026-06-20T12:00:00.000Z" },
        { balance: 2550, observedAt: "2026-07-20T12:00:00.000Z" },
        { balance: 2400, observedAt: V2_TEST_NOW },
      ]),
      ...snapshotSeries("household-seed", "household-medical", [
        { balance: 1500, observedAt: "2026-06-20T12:00:00.000Z" },
        { balance: 1500, observedAt: V2_TEST_NOW },
      ]),
      ...snapshotSeries("household-seed", "household-mortgage", [
        { balance: 121000, observedAt: "2026-06-20T12:00:00.000Z" },
        { balance: 120700, observedAt: V2_TEST_NOW },
      ]),
    },
    paymentEvents: {},
    expectedCheckpoints: Object.fromEntries(expectedCheckpoints.map((checkpoint) => [
      `${checkpoint.workspaceId}/${checkpoint.planId}/${checkpoint.planVersionId}/${checkpoint.id}`,
      checkpoint,
    ])),
  };
};
